# Generated by Django 4.2 on 2026-09-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('email', models.EmailField(blank=True, help_text='Optional, if they want a personal reply', max_length=254)),
                ('answer', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('answered', 'Answered')], default='new', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Submitted question',
                'verbose_name_plural': 'Submitted questions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visit request',
                'verbose_name_plural': 'Visit requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
